version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: "16:00"
    groups:
      actions:
        update-types:
          - "patch"
          - "minor"
          - "major"
